[package]
name = "tracingstuff"
version = "0.1.0"
edition = "2021"

[dependencies]
mini-redis = "0.4.1"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
